### ISSUE TITLE
Improve css and design of testimonials

### ISSUE THREAD

**Issue by Gobsmack90** [TBDG/waterfront#19]
have decorative quotations around quote blocks for example

**Comment by thorbaert** [comment]
We will need to get this arrow to stop hovering over the text I feel this needs to be done before we allow this to go to customers

I also think the dots should be removed if possible

![image](https://user-images.githubusercontent.com/22752236/104215727-6a92d500-53f6-11eb-8ca3-a8a304d38d7f.png)

**Comment by Gobsmack90** [comment]
I can get rid of the bottom very easy. I think I can fix the arrows. I'll
push an update today for that.

**Comment by thorbaert** [comment]
No worries I attached it to this ticket so it can all be done when we work on it

**Comment by Gobsmack90** [comment]
Ok

**Comment by thorbaert** [comment]
Should also put a max width on this whole thing so on large screens it is still readable

![image](https://user-images.githubusercontent.com/22752236/104223033-55bb3f00-5400-11eb-9556-9cb18a0440d0.png)
